---
# Manage Boot Disk (d0)
- name: gce manage instance boot disk
  google.cloud.gcp_compute_disk:
    name: "{{ gce_instance_name }}-boot"
    size_gb: "{{ gce_instance.disk.d0.size }}"
    type: "{{ gce_instance.disk.d0.type }}"
    source_image: "{{ gce_instance.disk.d0.image }}"
    zone: "{{ gce_instance_zone }}"
    project: "{{ gcp_project_id }}"
    auth_kind: "serviceaccount"
    service_account_file: "{{ gcp_service_account_file }}"
    scopes:
      - "{{ gcp_api_scopes.COMPUTE }}"
    state: "{{ gce_instance.disk.d0.state }}"
  register: gce_instance_disk_d0

- name: GCP Debug
  debug:
    var: gce_instance_disk_d0
  when: gcp_debug 

# Manage additional disks attached to the gce instance (d1,d2,d3,etc.)
- name: gce manage instance additional disks
  google.cloud.gcp_compute_disk:
    name: "{{ gce_instance_name }}-{{ item }}"
    size_gb: "{{ gce_instance.disk[item].size }}"
    type: "{{ gce_instance.disk[item].type }}"
    zone: "{{ gce_instance_zone }}"
    project: "{{ gcp_project_id }}"
    auth_kind: "serviceaccount"
    service_account_file: "{{ gcp_service_account_file }}"
    scopes:
      - "{{ gcp_api_scopes.COMPUTE }}"
    state: "{{ gce_instance.disk[item].state }}"
  register: gce_instance_disk
  with_items: "{{ gce_instance.disk }}"
  when: gce_instance.disk.d1.size|int > 0 and item != "d0"

- name: GCP Debug
  debug:
    var: gce_instance_disk.results
  when: gcp_debug 