---
- name: set public ip address
  set_fact:
    gce_instance_public_ip: "{{ network_interface_access_config[0].nat_ip.address }}"
  when: network_interface_access_config is defined

- name: set private ip address
  set_fact:
    gce_instance_private_ip: "{{ gce_instance_result.resources[0].networkInterfaces[0].networkIP }}"

- name: debug public ip address
  debug: 
    var: gce_instance_public_ip
  when: gcp_debug

- name: debug private ip address
  debug: 
    var: gce_instance_private_ip
  when: gcp_debug
