---
# IP ADDRESS
- name: debug ip config
  debug:
    var: gce_ip
  when: gcp_debug 

- name: manage gce ip address
  gcp_compute_address:
    name:       "{{ gce_ip.name }}-ip"
    region:     "{{ gce_ip.region }}"
    project:    "{{ gcp_project_id }}"
    auth_kind:  "serviceaccount"
    service_account_file: "{{ gcp_service_account_file }}"
    scopes:
       - "{{ gcp_api_scopes.COMPUTE }}"
    state: "{{ gce_ip.state }}"
  register: gce_ip_result

- name: debug ip result
  debug:
    var: gce_ip_result
  when: gcp_debug 