--- 
# ------------------------ #
# --- # VPC Network # ---  #
# ------------------------ #
- name: get info on the configured network
  gcp_compute_network_info:
    filters:
      - name = "{{ gce_network[0].name }}"
    project: "{{ gcp_project_id }}"
    auth_kind: "serviceaccount"
    service_account_file: "{{ gcp_service_account_file }}"
  register: gce_network_result
  when: gce_network[0] is defined

- name: debug network
  debug:
    var: gce_network_result
  when: gcp_debug

# ----------------------- #
# --- # Subnetwork # ---  #
# ----------------------- #
- name: get info on the selected subnetwork
  gcp_compute_subnetwork_info:
    region: "{{ gce_resource_region }}"
    filters:
      - name = "{{ gce_network[0].subnetwork }}"
    project: "{{ gcp_project_id }}"
    auth_kind: "serviceaccount"
    service_account_file: "{{ gcp_service_account_file }}"
  register: gce_subnetwork_result
  when: gce_network[0] is defined

- name: debug subnetwork
  debug:
    var: gce_subnetwork_result
  when: gcp_debug