--- 
# GCE NETWORK
- name: GCP Debug
  debug:
    var: network
  when: gcp_debug 

- name: manage gce network
  gcp_compute_network:
    name: "{{ network.n0.name }}"
    auto_create_subnetworks: "{{ network.n0.create_subnet }}"
    project: "{{ gcp_project.id }}"
    auth_kind: "serviceaccount"
    service_account_file: "{{ gcp_project.service_account_file }}"
    scopes:
      -  "{{ gcp_api_scopes.COMPUTE }}"
    state: "{{ network.n0.state }}"
  register: gce_network
