--- 
# GCE NETWORK
- name: debug network config
  debug:
    var: gce_network
  when: gcp_debug 

- name: manage gce network (present)
  gcp_compute_network:
    name: "{{ gce_network.n0.name }}"
    auto_create_subnetworks: "{{ gce_network.n0.create_subnet }}"
    project: "{{ gcp_project_id }}"
    auth_kind: "serviceaccount"
    service_account_file: "{{ gcp_service_account_file }}"
    scopes:
      -  "{{ gcp_api_scopes.COMPUTE }}"
    state: "{{ gce_network.n0.state }}"
  register: gce_network_result
  when: gce_network.n0.state == "present"

- name: manage gce network (absent)
  gcp_compute_network:
    name: "{{ gce_network.n0.name }}"
    project: "{{ gcp_project_id }}"
    auth_kind: "serviceaccount"
    service_account_file: "{{ gcp_service_account_file }}"
    scopes:
      -  "{{ gcp_api_scopes.COMPUTE }}"
    state: "{{ gce_network.n0.state }}"
  register: gce_network
  when: gce_network.n0.state == "absent"